### ISSUE TITLE
go17: panic on pat.Param

### ISSUE THREAD

**Issue by moorereason** [goji/goji#36]
Using the `go17` branch and running the example code from the README, I get a panic:

```
2016/09/02 12:37:34 http: panic serving 127.0.0.1:58164: interface conversion: interface is nil, not string
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc42005e400)
        /opt/go/src/net/http/server.go:1491 +0x12a
panic(0x6422e0, 0xc4200184c0)
        /opt/go/src/runtime/panic.go:458 +0x243
goji.io/pat.Param(0x7911c0, 0xc420015710, 0x687908, 0x4, 0x78dd40, 0x6a8a68)
        /opt/src/goji.io/pat/pat.go:303 +0xca
main.hello(0x790a00, 0xc420057ba0, 0xc4200b45a0)
        /opt/src/github.com/moorereason/gojitest/main.go:13 +0x63
net/http.HandlerFunc.ServeHTTP(0x6a8a68, 0x790a00, 0xc420057ba0, 0xc4200b45a0)
        /opt/go/src/net/http/server.go:1726 +0x44
goji%2eio.dispatch.ServeHTTP(0x790a00, 0xc420057ba0, 0xc4200b45a0)
        /opt/src/goji.io/dispatch.go:17 +0xd6
goji%2eio.(*dispatch).ServeHTTP(0x7c7de8, 0x790a00, 0xc420057ba0, 0xc4200b45a0)
        <autogenerated>:1 +0x6a
goji%2eio.(*Mux).ServeHTTP(0xc42005e200, 0x790a00, 0xc420057ba0, 0xc4200b45a0)
        /opt/src/goji.io/mux.go:74 +0x16b
net/http.serverHandler.ServeHTTP(0xc42005e380, 0x790a00, 0xc420057ba0, 0xc4200b42d0)
        /opt/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42005e400, 0x790f80, 0xc420018400)
        /opt/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2293 +0x44d
```
Offending line from main.go:
```go
    name := pat.Param(ctx, "name")
```

**Comment by ottob** [comment]
I get the same error with 1209a0b.

**Comment by zenazn** [comment]
Good catch! I fixed the bug and added a regression test.
