### ISSUE TITLE
go1.7.4 and go1.8: I try to unit test, but panic on pat.Param

### ISSUE THREAD

**Issue by mikey0119** [goji/goji#50]
```
go get goji.io
go get github.com/stretchr/testify
```

sample code[main.go]
```
package main
import (
	"fmt"
	"net/http"
	"goji.io"
	"goji.io/pat"
)

func hello(w http.ResponseWriter, r *http.Request) {
	name := pat.Param(r, "name")
	fmt.Fprintf(w, "Hello, %s!", name)
}

func main() {
	mux := goji.NewMux()
	mux.HandleFunc(pat.Get("/hello/:name"), hello)

	http.ListenAndServe("localhost:8000", mux)
}
```

test code[main_test.go]
```
package main
import (
        "net/http"
        "testing"
        "net/http/httptest"
        "github.com/stretchr/testify/assert"
)

func TestHello(t *testing.T) {
        t.Run("hello", func(t *testing.T) {
                t.Parallel()
                s := httptest.NewServer(http.HandlerFunc(hello))
                defer s.Close()
                res, err := http.Get(s.URL)
                assert.NoError(t, err)
                defer res.Body.Close()
        })
}
```

result
```
(go:test-go) [vagrant@localhost src]$ go test
2017/03/22 09:02:54 http: panic serving 127.0.0.1:48024: interface conversion: interface is nil, not string
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc42008e600)
        /home/vagrant/.gvm/gos/go1.7.4/src/net/http/server.go:1491 +0x12a
panic(0x66ae40, 0xc4200e8280)
        /home/vagrant/.gvm/gos/go1.7.4/src/runtime/panic.go:458 +0x243
goji.io/pat.Param(0xc4200d41e0, 0x6b49d3, 0x4, 0x0, 0xc4200707c0)
        /home/vagrant/workspace/test-go/src/goji.io/pat/pat.go:301 +0xe6
_/home/vagrant/workspace/test-go/src.hello(0x7d0cc0, 0xc4200fa000, 0xc4200d41e0)
        /home/vagrant/workspace/test-go/src/main.go:10 +0x47
net/http.HandlerFunc.ServeHTTP(0x6d8618, 0x7d0cc0, 0xc4200fa000, 0xc4200d41e0)
        /home/vagrant/.gvm/gos/go1.7.4/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42008e400, 0x7d0cc0, 0xc4200fa000, 0xc4200d41e0)
        /home/vagrant/.gvm/gos/go1.7.4/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42008e600, 0x7d1280, 0xc42001cb00)
        /home/vagrant/.gvm/gos/go1.7.4/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /home/vagrant/.gvm/gos/go1.7.4/src/net/http/server.go:2293 +0x44d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47689c]

goroutine 6 [running]:
panic(0x6693c0, 0xc42000c0d0)
        /home/vagrant/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008c240)
        /home/vagrant/.gvm/gos/go1.7.4/src/testing/testing.go:579 +0x25d
panic(0x6693c0, 0xc42000c0d0)
        /home/vagrant/.gvm/gos/go1.7.4/src/runtime/panic.go:458 +0x243
_/home/vagrant/workspace/test-go/src.TestHello.func1(0xc42008c240)
        /home/vagrant/workspace/test-go/src/main_test.go:16 +0xec
testing.tRunner(0xc42008c240, 0x6d8608)
        /home/vagrant/.gvm/gos/go1.7.4/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /home/vagrant/.gvm/gos/go1.7.4/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL    _/home/vagrant/workspace/test-go/src    0.010s
```

error is the same.
`res, err := http.Get(s.URL + "/hello/test")`

Thanks!!

**Comment by zenazn** [comment]
You'll need to specifically send a request through a Goji `Mux` in order to run Goji's routing logic. If Goji's routing logic doesn't run, it can't match its patterns against the input URL, and can't extract bound variables from the pattern (via e.g., `pat.Param`).

Try writing the following:

``` go
func mux() *goji.Mux {
	mux := goji.NewMux()
	mux.HandleFunc(pat.Get("/hello/:name"), hello)
        return mux
}

func main() {
	http.ListenAndServe("localhost:8000", mux())
}
```

And in your test, write `s := httptest.NewServer(mux())`
